{{- if .Values.virtualService.enabled -}}
{{- $fullName := include "code-server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  spec:
  gateways:
  - istio-system/apps-dns-ingressgateway
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: code-server
        port:
          number: {{ $svcPort }}
  {{- end }}
{{- end }}