{{- if .Values.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "code-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
    {{- with .Values.virtualservice.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    - {{ .Values.CodeServerUrl | quote }}
  gateways:
    - {{ .Values.virtualservice.gateways }}
  http:
    - match:
      - uri:
          prefix: "/"
      route:
        - destination:
            host: {{ include "code-server.fullname" . }}
            port:
              number: 80
{{- end }}